[package]
name = "quic"
version = "0.1.0"
edition = "2021"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cxx = { version = "1.0.83", features = ["c++20"] }
quinn-proto = { version = "0.11.9", features = ["platform-verifier"] }
